language: node_js

node_js:
  - 'lts/*'

script:
  - 'npm install -g codecov'
  - 'npm run bootstrap'
  - 'set -e'
  - 'npm run lint'
  - 'npm run test'

after_success:
  - 'npm run cover'
  - 'codecov'

notifications:
  email: false
