name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Install PNPM
      uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: |
          - recursive: true
            args: [--frozen-lockfile, --strict-peer-dependencies]
          - args: [--global, codecov]

    - name: Run the lint
      run: pnpm lint

    - name: Run the coverage
      run: pnpm cover

    - name: Run the coverage
      run: codecov
